// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { resolvePrismaCliDatasourceUrl } from './src/lib/database-url';

export default defineConfig({
	schema: 'prisma/schema.prisma',
	migrations: {
		path: 'prisma/migrations',
	},
	datasource: {
		url: resolvePrismaCliDatasourceUrl({
			NODE_ENV: process.env.NODE_ENV,
			VERCEL: process.env.VERCEL,
			VERCEL_ENV: process.env.VERCEL_ENV,
			DEV_DATABASE_URL: process.env.DEV_DATABASE_URL,
			PRODUCTION_DATABASE_URL: process.env.PRODUCTION_DATABASE_URL,
		}),
	},
});
